#!/usr/bin/env bash
# Generate the ansible inventory from the (deterministic) node topology.
# Only nodes whose domain is running are emitted, so plays target live hosts.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
preflight
ensure_dirs

out="${CLUSTER_INVENTORY_DIR}/hosts.ini"
{
  echo "# GENERATED by gen-inventory.sh — do not edit by hand."
  echo "[nodes]"
  for i in $(node_seq); do
    name="$(node_name "$i")"; ip="$(node_ip "$i")"
    dom_running "${name}" && printf '%s ansible_host=%s\n' "${name}" "${ip}"
  done
  echo
  echo "[nodes:vars]"
  echo "ansible_user=${CLUSTER_SSH_USER}"
  echo "ansible_ssh_private_key_file=${CLUSTER_SSH_PRIVKEY}"
  echo "ansible_python_interpreter=/usr/bin/python3"
  echo "cluster_net_cidr=${CLUSTER_NET_SUBNET}.0/24"
  # First-listed running node is the rank-0 / launcher for MPI hostfile assembly.
  first="$(for i in $(node_seq); do n="$(node_name "$i")"; dom_running "$n" && { echo "$n"; break; }; done)"
  echo "cluster_head_node=${first}"
} >"${out}"

log "wrote inventory: ${out}"
grep -c 'ansible_host=' "${out}" | xargs -I{} echo "  {} running node(s) listed"
